import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

const schema = a.schema({
  Expert: a
    .model({
      name: a.string().required(),
      role: a.string().required(),
      email: a.email(),
      phone: a.string(),
      category: a.string(),
      norma: a.integer().default(8),
      normType: a.string(),
      oreZi: a.float(),
      manualMonthlyNorm: a.float(),
      projectMonthlyNorm: a.float(),
      positionInProject: a.string(),
      projectCode: a.string(),
      projectTitle: a.string(),
      saCodes: a.string().array(),
      hasPmAccess: a.boolean().default(false),
      isActive: a.boolean().default(true),
      activities: a.hasMany("Activity", "expertId"),
      grupTintaEntries: a.hasMany("GrupTintaEntry", "expertId"),
    })
    .authorization((allow) => [
      allow.authenticated().to(["read"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  Activity: a
    .model({
      owner: a.string(),
      expertId: a.id().required(),
      expert: a.belongsTo("Expert", "expertId"),
      expertName: a.string(),
      date: a.date().required(),
      year: a.integer().required(),
      month: a.integer().required(),
      hours: a.float().required(),
      activityType: a.string().required(),
      saCode: a.string(),
      catalogActivityId: a.id(),
      title: a.string().required(),
      description: a.string(),
      location: a.string(),
      dayType: a.string(),
      workingGroupId: a.id(),
      status: a.string().default("draft"),
      shareStatus: a.string().default("private"),
      originActivityId: a.id(),
      takenByExperts: a.string().array(),
      projectCode: a.string(),
      autoGenerated: a.boolean().default(false),
      generatedAt: a.datetime(),
      generatedBy: a.string(),
      pmNotes: a.string(),
      deliverables: a.hasMany("Deliverable", "activityId"),
      grupTinta: a.hasMany("GrupTintaEntry", "activityId"),
    })
    .secondaryIndexes((index) => [
      index("expertId").sortKeys(["date"]),
      index("year").sortKeys(["month"]),
      index("shareStatus").sortKeys(["date"]),
      index("originActivityId"),
    ])
    .authorization((allow) => [
      allow.ownerDefinedIn("owner"),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  LegalHoliday: a
    .model({
      countryCode: a.string().default("RO"),
      date: a.date().required(),
      year: a.integer().required(),
      name: a.string().required(),
      type: a.string().required(),
      source: a.string(),
      sourceUrl: a.string(),
      notes: a.string(),
      isActive: a.boolean().default(true),
    })
    .secondaryIndexes((index) => [
      index("date"),
      index("year").sortKeys(["date"]),
    ])
    .authorization((allow) => [
      allow.authenticated().to(["read"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  Deliverable: a
    .model({
      owner: a.string(),
      activityId: a.id().required(),
      activity: a.belongsTo("Activity", "activityId"),
      fileName: a.string().required(),
      fileType: a.string().required(),
      fileSize: a.integer().required(),
      filePath: a.string(),
      documentId: a.id(),
      s3Bucket: a.string(),
      s3Key: a.string(),
      originalFileName: a.string(),
      fileHash: a.string(),
      firstPageTextHash: a.string(),
      contentFingerprint: a.string(),
      uploadedByExpertId: a.id(),
      uploadedByExpertName: a.string(),
      projectId: a.string(),
      projectName: a.string(),
      sourceActivityId: a.id(),
      activityDate: a.date(),
      saCode: a.string(),
      deliverableType: a.string(),
      isCommonDeliverable: a.boolean().default(false),
      sharedWithExpertIds: a.string().array(),
      possibleDuplicateOfDocumentId: a.id(),
      duplicateStatus: a.string(),
      uploadedAt: a.datetime(),
      declaredTitle: a.string(),
      docTitle: a.string(),
      docText: a.string(),
      suggestedTitle: a.string(),
      titleSuggestionConfidence: a.string(),
      titleSuggestionAlternatives: a.string().array(),
      titleSuggestionReason: a.string(),
      firstPageText: a.string(),
      titleSource: a.string(),
      titleMatch: a.boolean(),
      titleConfirmed: a.boolean(),
      titleCheckStatus: a.string(),
      titleCheckMessage: a.string(),
      aiStatus: a.string(),
      aiReason: a.string(),
      eligibilityCheck: a.json(),
    })
    .secondaryIndexes((index) => [index("activityId")])
    .authorization((allow) => [
      allow.ownerDefinedIn("owner"),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  Document: a
    .model({
      s3Bucket: a.string(),
      s3Key: a.string().required(),
      originalFileName: a.string().required(),
      mimeType: a.string().required(),
      fileSize: a.integer().required(),
      fileHash: a.string(),
      firstPageTextHash: a.string(),
      contentFingerprint: a.string(),
      uploadedByExpertId: a.id().required(),
      uploadedByExpertName: a.string(),
      uploadDate: a.datetime().required(),
      projectId: a.string(),
      projectName: a.string(),
      sourceActivityId: a.id(),
      activityDate: a.date(),
      saCode: a.string(),
      deliverableType: a.string(),
      declaredTitle: a.string(),
      suggestedTitle: a.string(),
      titleSuggestionConfidence: a.string(),
      titleSuggestionAlternatives: a.string().array(),
      titleSuggestionReason: a.string(),
      extractedTitle: a.string(),
      extractedTitleNormalized: a.string(),
      titleMatch: a.boolean(),
      titleCheckStatus: a.string(),
      eligibilityCheck: a.json(),
      isCommonDeliverable: a.boolean().default(false),
      possibleDuplicateOfDocumentId: a.id(),
      duplicateStatus: a.string(),
    })
    .secondaryIndexes((index) => [
      index("uploadedByExpertId").sortKeys(["uploadDate"]),
      index("projectId"),
      index("fileHash"),
      index("firstPageTextHash"),
    ])
    .authorization((allow) => [
      allow.authenticated().to(["create", "read", "update"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  SharedDeliverable: a
    .model({
      documentId: a.id().required(),
      sourceExpertId: a.id().required(),
      targetExpertId: a.id().required(),
      projectId: a.string(),
      sourceActivityId: a.id(),
      targetActivityId: a.id(),
      status: a.string().required(),
      notifiedAt: a.datetime(),
      registeredAt: a.datetime(),
      ignoredAt: a.datetime(),
      removedAt: a.datetime(),
    })
    .secondaryIndexes((index) => [
      index("documentId"),
      index("targetExpertId").sortKeys(["status"]),
      index("sourceExpertId"),
      index("projectId"),
    ])
    .authorization((allow) => [
      allow.authenticated().to(["create", "read", "update"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  GrupTintaEntry: a
    .model({
      owner: a.string(),
      expertId: a.id().required(),
      expert: a.belongsTo("Expert", "expertId"),
      activityId: a.id(),
      activity: a.belongsTo("Activity", "activityId"),
      date: a.date().required(),
      year: a.integer().required(),
      month: a.integer().required(),
      activityType: a.string().required(),
      organizations: a.string().array(),
      participantsCount: a.integer().default(0),
      notes: a.string(),
    })
    .secondaryIndexes((index) => [
      index("expertId").sortKeys(["date"]),
      index("year").sortKeys(["month"]),
    ])
    .authorization((allow) => [
      allow.ownerDefinedIn("owner"),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  ActivityCatalog: a
    .model({
      category: a.string().required(),
      saCode: a.string().required(),
      serviceCategory: a.string(),
      activityNumber: a.integer(),
      activityName: a.string().required(),
      description: a.string(),
      objectives: a.string(),
      serviceComponent: a.string(),
      beneficiaries: a.string(),
      expectedResults: a.string(),
      deliverables: a.string(),
      indicators: a.string(),
    })
    .secondaryIndexes((index) => [index("saCode")])
    .authorization((allow) => [
      allow.authenticated().to(["read"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  WorkingGroup: a
    .model({
      name: a.string().required(),
      type: a.string().required(),
      email: a.email(),
      isActive: a.boolean().default(true),
      saCode: a.string(),
      notes: a.string(),
    })
    .authorization((allow) => [
      allow.authenticated().to(["read"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  ReportStatus: a
    .model({
      expertId: a.id().required(),
      year: a.integer().required(),
      month: a.integer().required(),
      status: a.string().default("draft"),
      sentDate: a.datetime(),
      approvalDate: a.datetime(),
      expertAccessApproved: a.boolean().default(false),
      expertAccessApprovedAt: a.datetime(),
      pmNotes: a.string(),
    })
    .secondaryIndexes((index) => [index("expertId").sortKeys(["year", "month"])])
    .authorization((allow) => [
      allow.groups(["expert"]).to(["create", "read", "update"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  Verification: a
    .model({
      expertId: a.id().required(),
      expertName: a.string(),
      month: a.string().required(),
      year: a.string().required(),
      status: a.string().default("pending"),
      notes: a.string(),
      neconformitati: a.hasMany("Neconformitate", "verificationId"),
      verificationNotes: a.hasMany("VerificationNote", "verificationId"),
    })
    .secondaryIndexes((index) => [index("expertId").sortKeys(["year", "month"])])
    .authorization((allow) => [
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  Neconformitate: a
    .model({
      verificationId: a.id(),
      verification: a.belongsTo("Verification", "verificationId"),
      type: a.string().required(),
      severity: a.string().required(),
      description: a.string().required(),
      affectedDate: a.date(),
      affectedExpertId: a.id(),
      resolved: a.boolean().default(false),
      resolution: a.string(),
      resolvedAt: a.datetime(),
    })
    .secondaryIndexes((index) => [index("verificationId")])
    .authorization((allow) => [
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  VerificationNote: a
    .model({
      verificationId: a.id(),
      verification: a.belongsTo("Verification", "verificationId"),
      content: a.string().required(),
      category: a.string(),
      authorId: a.id(),
      authorName: a.string(),
    })
    .secondaryIndexes((index) => [index("verificationId")])
    .authorization((allow) => [
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  ConcurrentProject: a
    .model({
      expertId: a.id().required(),
      expertName: a.string(),
      projectName: a.string().required(),
      projectCode: a.string(),
      expertProjectRole: a.string(),
      fundingSource: a.string(),
      dailyHours: a.float().required(),
      startDate: a.date().required(),
      endDate: a.date(),
      isActive: a.boolean().default(true),
      notes: a.string(),
    })
    .secondaryIndexes((index) => [index("expertId")])
    .authorization((allow) => [
      allow.groups(["expert"]).to(["create", "read", "update"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  ConcurrentProjectTimesheetEntry: a
    .model({
      concurrentProjectId: a.id().required(),
      expertId: a.id().required(),
      date: a.date().required(),
      month: a.integer().required(),
      year: a.integer().required(),
      wp: a.string(),
      hours: a.float().required(),
      taskName: a.string(),
      relevantDeliverable: a.string(),
      dayType: a.string().required(),
      notes: a.string(),
      status: a.string().required(),
      source: a.string().required(),
      createdBy: a.string(),
      updatedBy: a.string(),
    })
    .secondaryIndexes((index) => [index("concurrentProjectId"), index("expertId"), index("month"), index("year")])
    .authorization((allow) => [
      allow.groups(["expert"]).to(["create", "read", "update"]),
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),

  AuditLog: a
    .model({
      actionType: a.string().required(),
      actorId: a.string().required(),
      actorName: a.string(),
      actorRole: a.string().required(),
      affectedExpertId: a.id(),
      affectedExpertName: a.string(),
      projectCode: a.string(),
      month: a.integer(),
      year: a.integer(),
      fieldName: a.string(),
      oldValue: a.string(),
      newValue: a.string(),
      justification: a.string(),
      source: a.string().required(),
    })
    .secondaryIndexes((index) => [
      index("affectedExpertId").sortKeys(["year", "month"]),
      index("actionType"),
    ])
    .authorization((allow) => [
      allow.groups(["pm"]).to(["create", "read"]),
      allow.groups(["admin"]).to(["create", "read", "update", "delete"]),
    ]),

  NotificationLog: a
    .model({
      kind: a.string().required(),
      recipientEmail: a.email().required(),
      subject: a.string().required(),
      body: a.string().required(),
      status: a.string().default("pending"),
      metadata: a.json(),
      sentAt: a.datetime(),
      errorMessage: a.string(),
    })
    .secondaryIndexes((index) => [index("kind"), index("recipientEmail")])
    .authorization((allow) => [
      allow.groups(["pm", "admin"]).to(["create", "read", "update", "delete"]),
    ]),
});

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool",
  },
});
