import assert from 'node:assert/strict';
import test from 'node:test';
import { buildDashboardComplianceRows } from '../lib/reporting-dashboard.ts';
import { generatePmMonthlyActivities } from '../lib/pm-auto-generation.ts';
import { buildMissingActivityEmailDrafts, buildWeeklyPmStatusEmailDraft } from '../lib/notification-jobs.ts';
import {
  buildExpertSubmittedMonthNotifications,
  buildPmApprovedMonthNotification,
  buildPmRequestedClarificationNotification,
  getPmNotificationRecipients,
} from '../lib/pm-email-notifications.ts';
import type { Activity, Expert } from '../lib/types.ts';

const pmExpert: Expert = {
  id: 'pm-1',
  name: 'PM Test',
  role: 'PM',
  email: 'pm@test.ro',
  norma: 8,
  normType: 'project',
  projectMonthlyNorm: 16,
  projectCode: '302141',
  isActive: true,
};

test('generarea PM nu depaseste 8 ore pe zi si marcheaza activitatile automat', () => {
  const existingActivities: Activity[] = [
    {
      id: 'a1',
      expertId: pmExpert.id,
      date: '2026-01-05',
      hours: 6,
      activityType: 'Management',
      title: 'Existenta',
    },
  ];

  const result = generatePmMonthlyActivities({
    expert: pmExpert,
    existingActivities,
    month: 0,
    year: 2026,
    actorId: 'admin-1',
    actorRole: 'admin',
    justification: 'Generare lunara pentru norma PM.',
    seed: 'test',
  });

  assert.equal(result.remainingUnallocatedHours, 0);
  assert.equal(result.activities.reduce((sum, activity) => sum + activity.hours, 0), 10);
  assert.ok(result.activities.every((activity) => activity.autoGenerated));
  assert.ok(result.activities.every((activity) => activity.hours <= 8));
  assert.equal(result.audit.actionType, 'pm_hours_generated');
});

test('dashboardul marcheaza zile lipsa, ore generate si interventii admin', () => {
  const rows = buildDashboardComplianceRows({
    experts: [pmExpert],
    activities: [
      {
        id: 'a1',
        expertId: pmExpert.id,
        date: '2026-01-05',
        hours: 8,
        activityType: 'Management',
        title: 'Management proiect',
        autoGenerated: true,
      },
    ],
    auditLogs: [
      {
        id: 'audit-1',
        actionType: 'pm_hours_generated',
        actorId: 'admin-1',
        actorRole: 'admin',
        createdAt: '2026-01-05T00:00:00.000Z',
        affectedExpertId: pmExpert.id,
        month: 0,
        year: 2026,
        source: 'automatic',
      },
    ],
    month: 0,
    year: 2026,
  });

  assert.equal(rows[0].totalHours, 8);
  assert.equal(rows[0].autoGeneratedHours, 8);
  assert.equal(rows[0].adminInterventions, 1);
  assert.ok(rows[0].missingActivityDays.length > 0);
});

test('emailul de activitate lipsa se trimite doar pentru zi lucratoare fara activitate', () => {
  const drafts = buildMissingActivityEmailDrafts({
    experts: [pmExpert],
    activities: [],
    today: new Date('2026-01-06T09:00:00.000Z'),
    appUrl: 'https://example.ro',
  });

  assert.equal(drafts.length, 1);
  assert.equal(drafts[0].kind, 'missing_activity');
  assert.equal(drafts[0].metadata?.date, '2026-01-05');
});

test('emailul saptamanal PM include statusul normei', () => {
  const draft = buildWeeklyPmStatusEmailDraft({
    pmEmails: ['pm@test.ro'],
    experts: [pmExpert],
    activities: [],
    month: 0,
    year: 2026,
    appUrl: 'https://example.ro',
  });

  assert.equal(draft.kind, 'pm_weekly_status');
  assert.match(draft.body, /PM Test/);
  assert.match(draft.body, /0\/16h/);
});

test('notificarile PM folosesc doar destinatarii PM activi si deduplicati', () => {
  const recipients = getPmNotificationRecipients([
    pmExpert,
    { ...pmExpert, id: 'pm-2', email: 'PM@test.ro', hasPmAccess: true },
    { ...pmExpert, id: 'expert-1', role: 'Expert', email: 'expert@test.ro', hasPmAccess: false },
    { ...pmExpert, id: 'admin-1', role: 'Admin aplicatie', email: 'admin@test.ro' },
    { ...pmExpert, id: 'inactive-pm', email: 'inactive@test.ro', hasPmAccess: true, isActive: false },
  ]);

  assert.deepEqual(recipients, ['pm@test.ro', 'admin@test.ro']);
});

test('submiterea expertului construieste notificari catre PM', () => {
  const drafts = buildExpertSubmittedMonthNotifications({
    expert: { ...pmExpert, id: 'expert-1', name: 'Expert Test', role: 'Expert', projectCode: '302141' },
    pmEmails: ['pm@test.ro', 'pm@test.ro'],
    month: 7,
    year: 2026,
  });

  assert.equal(drafts.length, 1);
  assert.equal(drafts[0].kind, 'pm_expert_month_submitted');
  assert.equal(drafts[0].recipientEmail, 'pm@test.ro');
  assert.match(drafts[0].subject, /Expert Test/);
});

test('actiunile PM construiesc notificari catre expert', () => {
  const expert = { ...pmExpert, id: 'expert-1', role: 'Expert', email: 'expert@test.ro' };
  const clarification = buildPmRequestedClarificationNotification({
    expert,
    month: 7,
    year: 2026,
    note: 'Te rog completeaza justificarea.',
  });
  const approval = buildPmApprovedMonthNotification({ expert, month: 7, year: 2026 });

  assert.equal(clarification[0].kind, 'pm_clarification_requested');
  assert.equal(clarification[0].recipientEmail, 'expert@test.ro');
  assert.match(clarification[0].body, /Te rog completeaza justificarea/);
  assert.equal(approval[0].kind, 'pm_month_approved');
});
