import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { buildPmKpiMetrics } from '../lib/pm-kpi-metrics.ts';
import type { DashboardComplianceRow, ReportStatus } from '../lib/types.ts';

const statusCounts: Record<ReportStatus['status'], number> = {
  draft: 1,
  sent: 2,
  in_review: 1,
  approved: 2,
  rejected: 0,
  clarifications: 1,
};

function row(expertId: string, overrides: Partial<DashboardComplianceRow> = {}): DashboardComplianceRow {
  return {
    expertId,
    expertName: expertId,
    role: 'Expert',
    month: 7,
    year: 2026,
    monthlyNorm: 100,
    activityCount: 1,
    missingDeliverableActivityCount: 0,
    totalHours: 100,
    autoGeneratedHours: 0,
    remainingHours: 0,
    utilizationPercent: 100,
    missingActivityDays: [],
    blockedDays: [],
    hasDailyLimitIssue: false,
    hasMonthlyNormIssue: false,
    hasProjectNormIssue: false,
    adminInterventions: 0,
    ...overrides,
  };
}

describe('buildPmKpiMetrics', () => {
  it('calculează KPI-urile PM din statusuri și rândurile dashboardului', () => {
    const metrics = buildPmKpiMetrics({
      dashboardRows: [
        row('approved-complete'),
        row('sent-complete'),
        row('clarifications-complete'),
        row('late-hours', { remainingHours: 12, utilizationPercent: 88 }),
        row('late-days', { missingActivityDays: ['2026-07-10'] }),
        row('approved-with-missing-deliverable', { missingDeliverableActivityCount: 1 }),
      ],
      reportStatusByExpertId: new Map([
        ['approved-complete', { status: 'approved' }],
        ['sent-complete', { status: 'sent' }],
        ['clarifications-complete', { status: 'clarifications' }],
        ['late-hours', { status: 'sent' }],
        ['late-days', { status: 'sent' }],
        ['approved-with-missing-deliverable', { status: 'approved' }],
      ]),
      statusCounts,
      problemCount: 7,
    });

    const values = Object.fromEntries(metrics.map((metric) => [metric.id, metric.value]));

    assert.equal(values.reporting_on_time, 3);
    assert.equal(values.verified_pm, 3);
    assert.equal(values.late, 2);
    assert.equal(values.approved_pm, 2);
    assert.equal(values.finalized, 1);
    assert.equal(values.action_needed, 7);
  });
});
