import assert from 'node:assert/strict';
import test from 'node:test';
import { buildPmReportSituation } from '../lib/pm-report-situation.ts';
import type { DashboardComplianceRow, Expert, ReportStatus } from '../lib/types.ts';

function expert(id: string, name: string): Expert {
  return { id, name, role: 'Expert', category: 'ap', norma: 8, isActive: true };
}

function status(expertId: string, value: ReportStatus['status']): ReportStatus {
  return { id: `status-${expertId}`, expertId, month: 7, year: 2026, status: value };
}

function dashboardRow(expertId: string, overrides: Partial<DashboardComplianceRow> = {}): DashboardComplianceRow {
  return {
    expertId,
    expertName: expertId,
    role: 'Expert',
    month: 7,
    year: 2026,
    totalHours: 0,
    autoGeneratedHours: 0,
    monthlyNorm: 100,
    remainingHours: 100,
    utilizationPercent: 0,
    normType: 'daily',
    missingActivityDays: [],
    blockedDays: [],
    missingDeliverableActivityCount: 0,
    hasDailyLimitIssue: false,
    hasMonthlyNormIssue: false,
    hasProjectNormIssue: false,
    adminInterventions: 0,
    activityCount: 0,
    ...overrides,
  };
}

test('construieste situatia de raportare PM din randuri si dashboard', () => {
  const experts = [expert('e1', 'Expert 1'), expert('e2', 'Expert 2'), expert('e3', 'Expert 3')];
  const submittedReportRows = [
    { expert: experts[0], status: status('e1', 'approved'), totalHours: 100, totalDeliverables: 2, issuesCount: 0, utilizationPercent: 100 },
    { expert: experts[1], status: status('e2', 'sent'), totalHours: 80, totalDeliverables: 1, issuesCount: 1, utilizationPercent: 80 },
    { expert: experts[2], status: status('e3', 'in_review'), totalHours: 100, totalDeliverables: 0, issuesCount: 0, utilizationPercent: 100 },
  ];
  const situation = buildPmReportSituation({
    experts,
    submittedReportRows,
    dashboardRows: [
      dashboardRow('e1', { totalHours: 100, remainingHours: 0, utilizationPercent: 100 }),
      dashboardRow('e2', { totalHours: 80, remainingHours: 20, utilizationPercent: 80 }),
      dashboardRow('e3', { totalHours: 100, remainingHours: 0, utilizationPercent: 100, missingDeliverableActivityCount: 1 }),
    ],
  });

  assert.equal(situation.proactiveRows.length, 2);
  assert.equal(situation.finishedRows.length, 1);
  assert.equal(situation.inProgressRows.length, 2);
  assert.deepEqual(situation.actionRows.map((row) => row.expertId), ['e2', 'e3']);
  assert.deepEqual(situation.cards.map((card) => [card.id, card.value]), [
    ['experts', 3],
    ['finished', 1],
    ['in_progress', 2],
    ['action_needed', 2],
  ]);
});
