import assert from 'node:assert/strict';
import test from 'node:test';

import { buildPmReportSituationWorkbookRows } from '../lib/pm-report-situation-export.ts';
import type { DashboardComplianceRow, Expert, ReportStatus } from '../lib/types.ts';

function expert(id: string, name: string): Expert {
  return { id, name, role: 'Expert raportare', category: 'ap', norma: 8, isActive: true };
}

function status(expertId: string, value: ReportStatus['status'], extras: Partial<ReportStatus> = {}): ReportStatus {
  return { id: `status-${expertId}`, expertId, month: 7, year: 2026, status: value, ...extras };
}

function dashboardRow(expertId: string, overrides: Partial<DashboardComplianceRow> = {}): DashboardComplianceRow {
  return {
    expertId,
    expertName: expertId,
    role: 'Expert raportare',
    month: 7,
    year: 2026,
    totalHours: 100,
    autoGeneratedHours: 0,
    monthlyNorm: 100,
    remainingHours: 0,
    utilizationPercent: 100,
    normType: 'daily',
    missingActivityDays: [],
    blockedDays: [],
    missingDeliverableActivityCount: 0,
    hasDailyLimitIssue: false,
    hasMonthlyNormIssue: false,
    hasProjectNormIssue: false,
    adminInterventions: 0,
    activityCount: 10,
    ...overrides,
  };
}

const statusLabels = {
  draft: { label: 'Draft' },
  sent: { label: 'Trimis catre PM' },
  in_review: { label: 'In verificare' },
  approved: { label: 'Aprobat' },
  rejected: { label: 'Respins' },
  clarifications: { label: 'Clarificari' },
} satisfies Record<ReportStatus['status'], { label: string }>;

test('construieste randurile XLSX pentru situatia de raportare PM', () => {
  const experts = [expert('e1', 'Expert 1'), expert('e2', 'Expert 2')];
  const approved = status('e1', 'approved', {
    sentDate: '2026-08-01T10:00:00.000Z',
    approvalDate: '2026-08-02T10:00:00.000Z',
  });
  const sent = status('e2', 'sent', {
    sentDate: '2026-08-01T12:00:00.000Z',
  });

  const rows = buildPmReportSituationWorkbookRows({
    experts,
    submittedReportRows: [
      { expert: experts[0], status: approved, totalHours: 100, totalDeliverables: 3, issuesCount: 0, utilizationPercent: 100 },
      { expert: experts[1], status: sent, totalHours: 80, totalDeliverables: 1, issuesCount: 1, utilizationPercent: 80 },
    ],
    dashboardRows: [
      dashboardRow('e1'),
      dashboardRow('e2', { totalHours: 80, remainingHours: 20, utilizationPercent: 80, missingDeliverableActivityCount: 1 }),
    ],
    reportStatusByExpertId: new Map([
      ['e1', approved],
      ['e2', sent],
    ]),
    statusLabels,
    month: 7,
    year: 2026,
    projectCode: '302141',
  });

  assert.equal(rows.summaryRows[0].Valoare, '302141');
  assert.equal(rows.statusRows.length, 2);
  assert.equal(rows.statusRows[0].Expert, 'Expert 1');
  assert.equal(rows.statusRows[0]['Status raportare'], 'Aprobat');
  assert.equal(rows.statusRows[0]['Data aprobarii'], '2026-08-02');
  assert.equal(rows.actionRows.length, 1);
  assert.equal(rows.actionRows[0].Expert, 'Expert 2');
  assert.match(rows.actionRows[0].Motiv, /20h ramase/);
  assert.match(rows.actionRows[0].Motiv, /1 livrabile lipsa/);
});
