import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { buildPmTimesheetViewModel } from '../lib/pm-timesheet-view.ts';
import type { Activity, DashboardComplianceRow, DocumentMetadata, Expert } from '../lib/types.ts';

const experts: Expert[] = [
  { id: 'e1', name: 'Andreea Cojocaru', role: 'Expert', norma: 5 },
  { id: 'e2', name: 'Radu Ianos', role: 'Expert', norma: 6 },
];

function row(expertId: string, overrides: Partial<DashboardComplianceRow> = {}): DashboardComplianceRow {
  return {
    expertId,
    expertName: expertId,
    month: 7,
    year: 2026,
    monthlyNorm: 126,
    activityCount: 1,
    missingDeliverableActivityCount: 0,
    totalHours: 58,
    autoGeneratedHours: 0,
    remainingHours: 68,
    utilizationPercent: 46,
    missingActivityDays: [],
    blockedDays: [],
    hasDailyLimitIssue: false,
    hasMonthlyNormIssue: false,
    hasProjectNormIssue: false,
    adminInterventions: 0,
    ...overrides,
  };
}

function activity(id: string, overrides: Partial<Activity> = {}): Activity {
  return {
    id,
    expertId: 'e1',
    date: '2026-08-03',
    hours: 6,
    activityType: 'Analiză',
    title: 'Analiza oportunităților europene',
    ...overrides,
  };
}

function document(id: string, overrides: Partial<DocumentMetadata> = {}): DocumentMetadata {
  return {
    id,
    s3Key: `${id}.pdf`,
    originalFileName: `${id}.pdf`,
    mimeType: 'application/pdf',
    fileSize: 100,
    uploadedByExpertId: 'e1',
    uploadDate: '2026-08-12T08:00:00.000Z',
    ...overrides,
  };
}

describe('buildPmTimesheetViewModel', () => {
  it('selectează expertul, marchează activitățile blocate și separă cazurile auto-rezolvate', () => {
    const model = buildPmTimesheetViewModel({
      experts,
      dashboardRows: [row('e1'), row('e2', { totalHours: 100, utilizationPercent: 80 })],
      activities: [
        activity('a1'),
        activity('a2', { date: '2026-08-04' }),
        activity('other', { expertId: 'e2' }),
      ],
      activeBlockedDocuments: [
        document('blocked', {
          sourceActivityId: 'a1',
          eligibilityCheck: {
            status: 'neeligibil',
            score: 30,
            summary: 'Neeligibil',
            checks: [],
            missingElements: [],
            recommendations: [],
            riskFlags: [],
            pmUnlockRequested: true,
          },
        }),
      ],
      autoResolvedDocuments: [
        document('resolved', {
          sourceActivityId: 'a2',
          eligibilityCheck: {
            status: 'eligibil',
            score: 90,
            summary: 'Corectat',
            checks: [],
            missingElements: [],
            recommendations: [],
            riskFlags: [],
            pmUnlockRequested: true,
            pmUnlockResolvedByCorrection: true,
          },
        }),
      ],
      selectedExpertId: 'e1',
      selectedMonth: 7,
      selectedYear: 2026,
    });

    assert.equal(model.selectedExpert?.id, 'e1');
    assert.equal(model.selectedActivities.length, 2);
    assert.equal(model.selectedActiveBlockedDocuments.length, 1);
    assert.equal(model.selectedAutoResolvedDocuments.length, 1);
    assert.equal(model.blockedActivityIds.has('a1'), true);
    assert.equal(model.blockedActivityIds.has('a2'), false);
    assert.equal(model.activitiesByDay.get('2026-08-03')?.length, 1);
    assert.equal(model.calendarDays.find((day) => day.date === '2026-08-03')?.status, 'blocked');
    assert.equal(model.calendarDays.find((day) => day.date === '2026-08-04')?.status, 'worked');
    assert.equal(model.calendarDays.find((day) => day.date === '2026-08-05')?.status, 'missing_timesheet');
    assert.equal(model.expertChips.find((chip) => chip.expert.id === 'e1')?.isActive, true);
  });
});
