import { calculateMonthlyNormInfo, DAILY_HOURS_LIMIT, totalActivityHours } from './pontaj-rules.ts';
import type { Activity, AuditLog, Expert } from './types.ts';
import { createAuditLog } from './audit-trail.ts';
import { getWorkingDaysListInMonth } from './working-hours.ts';

export interface PmGenerationResult {
  activities: Omit<Activity, 'id' | 'createdAt' | 'updatedAt'>[];
  audit: AuditLog;
  remainingUnallocatedHours: number;
}

function seededRandom(seed: string) {
  let hash = 2166136261;
  for (let index = 0; index < seed.length; index += 1) {
    hash ^= seed.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }

  return () => {
    hash += 0x6d2b79f5;
    let next = hash;
    next = Math.imul(next ^ (next >>> 15), next | 1);
    next ^= next + Math.imul(next ^ (next >>> 7), next | 61);
    return ((next ^ (next >>> 14)) >>> 0) / 4294967296;
  };
}

function isoDate(date: Date) {
  return date.toISOString().slice(0, 10);
}

function existingDailyTotals(activities: Pick<Activity, 'date' | 'hours'>[]) {
  const totals = new Map<string, number>();
  activities.forEach((activity) => {
    totals.set(activity.date, (totals.get(activity.date) ?? 0) + (Number(activity.hours) || 0));
  });
  return totals;
}

export function generatePmMonthlyActivities(args: {
  expert: Expert;
  existingActivities: Activity[];
  month: number;
  year: number;
  actorId: string;
  actorName?: string;
  actorRole: string;
  justification: string;
  projectCode?: string;
  seed?: string;
}): PmGenerationResult {
  const role = (args.expert.role || '').toLowerCase();
  if (!role.includes('pm')) {
    throw new Error('Generarea automata este permisa doar pentru rol PM sau Expert/PM.');
  }

  const normInfo = calculateMonthlyNormInfo(args.expert, args.month, args.year);
  const existingMonthHours = totalActivityHours(args.existingActivities);
  let remainingToAllocate = Math.max(0, normInfo.monthlyNorm - existingMonthHours);
  const dailyTotals = existingDailyTotals(args.existingActivities);
  const workingDays = getWorkingDaysListInMonth(args.month + 1, args.year)
    .map(isoDate)
    .filter((date) => (dailyTotals.get(date) ?? 0) < DAILY_HOURS_LIMIT);
  const random = seededRandom(args.seed ?? `${args.expert.id}:${args.year}:${args.month}`);
  const shuffledDays = [...workingDays].sort(() => random() - 0.5);
  const generatedAt = new Date().toISOString();
  const generated: Omit<Activity, 'id' | 'createdAt' | 'updatedAt'>[] = [];

  for (const date of shuffledDays) {
    if (remainingToAllocate <= 0) break;

    const availableForDay = Math.max(0, DAILY_HOURS_LIMIT - (dailyTotals.get(date) ?? 0));
    if (availableForDay <= 0) continue;

    const hours = Math.min(availableForDay, remainingToAllocate);
    generated.push({
      expertId: args.expert.id,
      expertName: args.expert.name,
      date,
      hours,
      activityType: 'Management',
      saCode: 'PM',
      title: 'Management proiect',
      description: 'Ore generate automat pentru rol PM.',
      status: 'approved',
      projectCode: args.projectCode ?? args.expert.projectCode,
      autoGenerated: true,
      generatedAt,
      generatedBy: args.actorId,
    });
    dailyTotals.set(date, (dailyTotals.get(date) ?? 0) + hours);
    remainingToAllocate -= hours;
  }

  const audit = createAuditLog({
    actionType: 'pm_hours_generated',
    actorId: args.actorId,
    actorName: args.actorName,
    actorRole: args.actorRole,
    affectedExpertId: args.expert.id,
    affectedExpertName: args.expert.name,
    projectCode: args.projectCode ?? args.expert.projectCode,
    month: args.month,
    year: args.year,
    fieldName: 'autoGeneratedHours',
    oldValue: existingMonthHours,
    newValue: existingMonthHours + totalActivityHours(generated),
    justification: args.justification,
    source: 'automatic',
  });

  return {
    activities: generated,
    audit,
    remainingUnallocatedHours: remainingToAllocate,
  };
}
