import { calculateMonthlyNormInfo, DAILY_HOURS_LIMIT, totalActivityHours } from './pontaj-rules.ts';
import type { Activity, AuditLog, DashboardComplianceRow, Expert } from './types.ts';
import { getWorkingDaysListInMonth } from './working-hours.ts';

function isoDate(date: Date) {
  return date.toISOString().slice(0, 10);
}

function datesWithTotals(activities: Pick<Activity, 'date' | 'hours'>[]) {
  const totals = new Map<string, number>();
  activities.forEach((activity) => {
    totals.set(activity.date, (totals.get(activity.date) ?? 0) + (Number(activity.hours) || 0));
  });
  return totals;
}

export function buildDashboardComplianceRows(args: {
  experts: Expert[];
  activities: Activity[];
  auditLogs?: AuditLog[];
  month: number;
  year: number;
}): DashboardComplianceRow[] {
  const workingDays = getWorkingDaysListInMonth(args.month + 1, args.year).map(isoDate);

  return args.experts
    .filter((expert) => expert.isActive !== false)
    .map((expert) => {
      const expertActivities = args.activities.filter((activity) => activity.expertId === expert.id);
      const normInfo = calculateMonthlyNormInfo(expert, args.month, args.year);
      const dayTotals = datesWithTotals(expertActivities);
      const activityCount = expertActivities.length;
      const missingDeliverableActivityCount = expertActivities.filter((activity) => (activity.deliverables?.length ?? 0) === 0).length;
      const totalHours = totalActivityHours(expertActivities);
      const autoGeneratedHours = totalActivityHours(expertActivities.filter((activity) => activity.autoGenerated));
      const missingActivityDays = workingDays.filter((date) => (dayTotals.get(date) ?? 0) === 0);
      const blockedDays = Array.from(dayTotals.entries())
        .filter(([, hours]) => hours >= DAILY_HOURS_LIMIT)
        .map(([date]) => date);
      const remainingHours = Math.max(0, normInfo.monthlyNorm - totalHours);
      const utilizationPercent = normInfo.monthlyNorm > 0 ? Math.round((totalHours / normInfo.monthlyNorm) * 100) : 0;
      const adminInterventions =
        args.auditLogs?.filter((log) => log.affectedExpertId === expert.id && log.month === args.month && log.year === args.year).length ?? 0;

      return {
        expertId: expert.id,
        expertName: expert.name,
        role: expert.role,
        category: expert.category,
        projectCode: expert.projectCode,
        month: args.month,
        year: args.year,
        normType: normInfo.normType,
        monthlyNorm: normInfo.monthlyNorm,
        projectNorm: expert.projectMonthlyNorm,
        activityCount,
        missingDeliverableActivityCount,
        totalHours,
        autoGeneratedHours,
        remainingHours,
        utilizationPercent,
        missingActivityDays,
        blockedDays,
        hasDailyLimitIssue: Array.from(dayTotals.values()).some((hours) => hours > DAILY_HOURS_LIMIT),
        hasMonthlyNormIssue: totalHours > normInfo.monthlyNorm,
        hasProjectNormIssue: normInfo.normType === 'project' && totalHours > normInfo.monthlyNorm,
        adminInterventions,
      };
    });
}
